name: "Continuous Integration"

description: "Build and run tests."

inputs:
  java-version:
    required: false
    type: string
    default: "17"

runs:
  using: "composite"
  steps:
    - name: "Checkout sources"
      uses: actions/checkout@v4

    - name: "Set up JDK"
      uses: actions/setup-java@v3
      with:
        distribution: "temurin"
        java-version: ${{ inputs.java-version }}
        cache: maven

    - name: "Build and run tests"
      run: mvn install
      shell: bash
