name: "Continuous Integration"

description: "Build and run tests."

inputs:
  node-version:
    required: false
    type: string
    default: "18.x"

runs:
  using: "composite"
  steps:
    - name: "Checkout sources"
      uses: actions/checkout@v4

    - name: "Setup NodeJS"
      uses: actions/setup-node@v3
      with:
        node-version: ${{ inputs.node-version }}

    - name: "Install dependencies"
      run: yarn install
      shell: bash

    - name: "Run tests"
      run: yarn test
      shell: bash

